### ISSUE TITLE
Not Recording WoW War Games

### ISSUE THREAD

**Issue by b3h47pte** [csutcliff/SimpleCombatLogger#1]
Seems like some SquadOV users want to record war games (on the tournament realm?).

It doesn't seem like any of the checks in SCL check for this particular condition. I'm thinking using this API call could work? https://wowpedia.fandom.com/wiki/API_IsWargame

**Comment by csutcliff** [comment]
Hi Mike,

That wasn't something I was even aware of existing, it should work fine to just add a check using that API call. If you want to submit a pull request that would be great, otherwise I am on holiday now until 28th and I can have a look when I get back.

**Comment by Xyphers** [comment]
I can create a toggle for this tomorrow after @csutcliff approves my other pull request.

**Comment by csutcliff** [comment]
> I can create a toggle for this tomorrow after @csutcliff approves my other pull request.

I had forgotten about this, sorry! If you do get a chance to add this I'll release with the other PR you made.
